language: csharp
solution: nanoid-net.sln
matrix:
  include:
    - os: osx
      osx_image: xcode11
      dotnet: 3.1.101
      mono: none
    - os: linux
      dist: bionic
      sudo: required
      dotnet: 3.1.100
      mono: none

branches:
  only:
    - master
before_script:
  - |
    set -e
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        ulimit -n 1024
    fi
    dotnet restore
script:
  - dotnet build "src\Nanoid"
  - dotnet build "test\Nanoid.Test" -c Release
  - dotnet test "test\Nanoid.Test\Nanoid.Test.csproj" --configuration Release --no-build --framework netcoreapp3.0